// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkzMv03IDFSdy8BrhQQOpPMY76wK298vI',
    appId: '1:466090566275:web:216c8a49d90bc0ef1ef1b6',
    messagingSenderId: '466090566275',
    projectId: 'ecommerce-app-204c0',
    authDomain: 'ecommerce-app-204c0.firebaseapp.com',
    storageBucket: 'ecommerce-app-204c0.appspot.com',
    measurementId: 'G-QL0T68NPXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOi31q71L3R_Fn6Yn7TKeF4c-JMp4dsHQ',
    appId: '1:466090566275:android:4c8ec53b0ff5b4ee1ef1b6',
    messagingSenderId: '466090566275',
    projectId: 'ecommerce-app-204c0',
    storageBucket: 'ecommerce-app-204c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQJ4QqptwxiJt2BTLmrld4RjbSckViJzw',
    appId: '1:466090566275:ios:d22c8bf16db1d9f11ef1b6',
    messagingSenderId: '466090566275',
    projectId: 'ecommerce-app-204c0',
    storageBucket: 'ecommerce-app-204c0.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQJ4QqptwxiJt2BTLmrld4RjbSckViJzw',
    appId: '1:466090566275:ios:d22c8bf16db1d9f11ef1b6',
    messagingSenderId: '466090566275',
    projectId: 'ecommerce-app-204c0',
    storageBucket: 'ecommerce-app-204c0.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkzMv03IDFSdy8BrhQQOpPMY76wK298vI',
    appId: '1:466090566275:web:0d037834428c820a1ef1b6',
    messagingSenderId: '466090566275',
    projectId: 'ecommerce-app-204c0',
    authDomain: 'ecommerce-app-204c0.firebaseapp.com',
    storageBucket: 'ecommerce-app-204c0.appspot.com',
    measurementId: 'G-SCQ8W1JXZJ',
  );
}
